### ISSUE TITLE
[BUG] tw_gtasks_sync syncing waiting tasks from other project

### ISSUE THREAD

**Issue by kstreser** [bergercookie/syncall#110]
### Describe the bug

Tasks with status "waiting" getting synchronized from a Project, that has not been specified and the tasks don't match the given tag.

### To Reproduce

```
task add project:A wait:2w Lorem ipsum dolor
tw_gtasks_sync -l B_inbox -f project:B -t in
```

### Expected Behavior

Only tasks from project B with tag "in" get synchronized

#### OS Version (`cat /etc/*-release; uname -a`)

```
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
Linux archlinux 6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64 GNU/Linux
```

#### Python version (`python --version; python3 --version`)

```
Python 3.11.7
Python 3.11.7
```

#### `--version` of your executable

I'm getting this string from tw_gtasks_sync --version:
`
tw_gtasks_sync, version <module 'syncall.__version__' from '/home/<user>/.local/share/pipx/venvs/syncall/lib/python3.11/site-packages/syncall/__version__.py'>`

Contents of this file:
```

# These version placeholders will be replaced later during substitution.
__version__ = "1.8.5"                                                   
__version_tuple__ = (1, 8, 5)     
```

**Comment by dickscheid** [comment]
I have only seen this now. I just submitted a tiny PR which fixes this problem for me:
https://github.com/bergercookie/taskw-ng/pull/1

**Comment by bergercookie** [comment]
@dickscheid 's fix is now in the latest taskw-ng and in the latest syncall version (`v.1.8.6`).

Closing this issue as completed but do shout if the fix is not working for you.
