### ISSUE TITLE
[BUG] Missing pkg_resources for Python >= 3.12

### ISSUE THREAD

**Issue by kstreser** [bergercookie/syncall#113]
### Describe the bug

syncall/google/gtasks_side.py imports pkg_resources which is part of setuptools. This pkg_resources deprecated and will not be installed by default in virtual environments for Python >= 3.12 (see https://github.com/python/cpython/issues/95299). A workaround might be to run `pip install setuptools` in the virtual environment but this is not clear from the given error. A solution might be to configure a dependency to setuptools for the package.

### To Reproduce
Upgrade python to 3.12.
Create venv with `python -m venv .venv`.
Activate venv with `source .venv/bin/activate`
`pip install syncall[google,tw]`
`tw_gtasks_sync --help`
`2024-05-04 12:07:53.418 | ERROR    | syncall.app_utils:inform_about_app_extras:242 - 
You have to install the google,tw extras for tw_gtasks_sync to work.
With pip, you can do it with something like: "pip3 install syncall[google,tw]"
Exiting.
`

#### OS Version (`cat /etc/*-release; uname -a`)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
Linux archlinux 6.8.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000 x86_64 GNU/Linux

#### Python version (`python --version; python3 --version`)

Python 3.12.3
Python 3.12.3

#### `--version` of your executable

1.8.5

**Comment by bergercookie** [comment]
Please have a look at the latest state of master and if it still exists, let's re-open this!

Thanks for the bug report!
