### ISSUE TITLE
[BUG] `twgcalsyncduration` UDA has no effect on google calendar event duration

### ISSUE THREAD

**Issue by jemorriso** [bergercookie/syncall#114]
### Describe the bug

`twgcalsyncduration` UDA has no effect on google calendar event duration. It doesn't matter what it is, each event is just half an hour, unless you use `--default-event-duration` which does change the event duration on google calendar.

### To Reproduce

In `.taskrc`:
```shell
uda.twgcalsyncduration.type=duration
uda.twgcalsyncduration.label=GCal duration
```

Add task and modify duration:
`task add task 1`
`task mod 1 twgcalsyncduration:180min`

`task edit 1` shows the UDA is correctly set.

### Expected Behavior

The event duration on google calendar should be 180 minutes.

#### OS Version

Darwin Jeremys-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

#### Python version (`python --version; python3 --version`)

python 3.11.7

#### `--version` of your executable

tw_gcal_sync, version <module 'syncall.__version__' from '/Users/jerry/venvs/syncall/.venv/lib/python3.11/site-packages/syncall/__version__.py'>

### Additional context

I also tried `syncallduration` which also did not work.

**Comment by bergercookie** [comment]
Hi @jemorriso , 

Thanks for reporting this.
The docs were out of date, the name of the UDA is `syncallduration`. I've now updated them.

> I also tried syncallduration which also did not work.

Hmm, I've just tried with the latest master version of this tool (I'm at commit 2f0abd9) and it worked fine. I've added a task like this from CLI `task add  +test2 syncallduration:2h kalispera due:3h` and I'm seeing that the duration in the Google Calendar event is indeed 2 hours.

Could you test it again?

I'm closing this issue but feel free to get back if that doesn't work and I'll re-open
