### ISSUE TITLE
set reminder when sync to Google Calendar

### ISSUE THREAD

**Issue by alfredoq** [bergercookie/syncall#118]
hello,

is it possible to make Syncall set the reminder field to a specific value when synching the tasks to Google Calendar?  I see that due dates are indeed configures, howere the Reminder field of the event is set to "No reminder".

Thank you in advance for the info

**Comment by bergercookie** [comment]
Hi @alfredoq

Last time I checked that wasn't possible with the Google Calendar API unfortunately.
Please use the TW <> Google Tasks integration which allows for setting reminders based on the date (not the time part) - see [this](https://github.com/bergercookie/syncall/blob/master/docs/readme-tw-gtasks.md#notes-re-this-synchronization) for more.
