### ISSUE TITLE
Update repository topics

### ISSUE THREAD

**Issue by lauft** [bergercookie/syncall#119]
Your repository is listed on the [*Taskwarrior* tools list](https://taskwarrior.org/tools), thanks for contributing! :heart:

We want to inform you about some changes to the crawler script collecting the tool information from GitHub:

Your tool is listed because it has the keyword `taskwarrior` among its topics.

With the release of *Taskwarrior 3* and its changes to task synchronization, we want to improve the tool listings by showing whether it is intended for *Taskwarrior 2*, *Taskwarrior 3*, and/or *Taskserver*.

Your tools with topic `taskwarrior` will be listed on the tools page as intended for both, *Taskwarrior 2* and *Taskwarrior 3*.
If this is correct, then there is nothing else to do – just close the issue. :slightly_smiling_face:
However, if your tool is only working with *Taskwarrior 2*, we would ask you to update your topic to `taskwarrior2` instead.

For further questions and details, you can go to [this GitHub discussion](https://github.com/GothenburgBitFactory/taskwarrior/discussions/3490).
Thank you very much for your support!

**Comment by bergercookie** [comment]
Thanks! This tool should still be relevant for both TW2 and TW3 given that the changse are only relevant to task synchronization
