### ISSUE TITLE
Sync as Google Tasks

### ISSUE THREAD

**Issue by soraxas** [bergercookie/syncall#21]
It would be great to have options to be synced as Google Tasks, or Google Reminder, rather than as events

**Comment by bergercookie** [comment]
There's no public API for Google reminders unfortunately, that was my original objective as well.
Wrt google tasks, sure, that would be a great feature to have.

Syncing over calendar events currently works fine for me so I'm not super keen on implementing it, at least not now.

It is a valid request though and it would be super useful to have so if somebody wants to work on it in the meantime, let me know ^_^

**Comment by JulianTao** [comment]
Hello, is there any progress on this feature request? It will be extremely useful for me especially since there is a shortcut (T) to add an email as a task.

**Comment by bergercookie** [comment]
> a new "Tasks" calendar is created in gcal. Am I doing something wrong?

Even though Google tasks are displayed in your google calendar, it's just a view, and not an actual calendar, hence the tool creates a new calendar with the same name.

I currently have no plans of implementing this right now.

**Comment by cenktaskin** [comment]
Hey, I would like to see this implemented. There were other apps using Tasks API, [example](https://tasksboard.com/), although I've no idea how cumbersome it would be to implement.

I've quite bit of Python proficiency, and a bit on bash as well, but I've never worked on a large project, rather on data-science pipelines or academical work. Nevertheless, I can try my best in case you can mentor the process @bergercookie .

Cheers

**Comment by bergercookie** [comment]
Hi @cenktaskin ,

This should definitely be possible. Feel free to have a go and let me know if you have any questions (e.g., start a thread in the [Discussions](https://github.com/bergercookie/taskwarrior-syncall/discussions)) :-)

See also this issue for potential sources of inspiration on creating this new synchronisation - https://github.com/bergercookie/taskwarrior-syncall/issues/61

**Comment by cenktaskin** [comment]
> See also this issue for potential sources of inspiration on creating this new synchronisation - #61
Just saw the guide on the thread you linked, thanks for that! Looks really helpful.

**Comment by cenktaskin** [comment]
> Nevertheless, I can try my best in case you can mentor the process @bergercookie .

Unfortunately I have switched from google products a while ago, so I don't have such necessary means, and honestly the motivation to work on this. Hope someone else supports the effort!
