### ISSUE TITLE
[BUG] setting calendar description "status: completed: moves task to odd time with weird title

### ISSUE THREAD

**Issue by bcohen44** [bergercookie/syncall#67]
❗❗❗ Please have a close look at the logs before posting them here. Amend the
logs if you see your username or password there.

### To Reproduce
_Note, I am using scheduled time_

1. enter task in tw, scheduled for today at some time
2. sync
3. in Gcal, edit event descripts, change to `status: completed"
4. sync

### Expected Behavior

event updates with check mark emoji, w/o moving the scheduled time

### 📸 Screenshots
![image](https://user-images.githubusercontent.com/6190190/213493851-5d5b385e-ccfe-40c8-9c9f-00432d23e074.png)

**Comment by bergercookie** [comment]
This is dealt with in another resolved issue - https://github.com/bergercookie/syncall/issues/69

Closing this
