### ISSUE TITLE
Setting scheduled today for "sched:today" set the task for 11:30PM previous day

### ISSUE THREAD

**Issue by bcohen44** [bergercookie/syncall#68]
task info  in tw, 
`Scheduled     2023-01-19 00:00:00`

Calendar:
![image](https://user-images.githubusercontent.com/6190190/213494374-3eb72966-434b-447c-926b-3487f1cfaa2d.png)

**Comment by kamillentee** [comment]
Taskwarrior can save dates only in UTC. 
Solutions:
1. Feature to allow taskwarrior specifying its default timezone
2. Feature to convert dates using syncall to your default timezone
(3.) Switch to UTC within google calendar

**Comment by bergercookie** [comment]
This isn't a bug. Fo an item that's (TW) due:today, we create an event in Google Calendar that has event end == today, i.e., midngiht. We also set the start of the event to (event end - syncallduration).

See https://github.com/bergercookie/syncall/blob/419226d5408b4b0d037cae917ef6b1b39e2218f7/syncall/tw_gcal_utils.py#L79-L113
