### ISSUE TITLE
Environment variables no longer supported?

### ISSUE THREAD

**Issue by PMunch** [bergercookie/syncall#75]
Tried to get GKeep sync set up again after the authorization bugs was apparently fixed. Unfortunately my original script now fails with:

```
bubop.exceptions.NoSuchFileOrDirectoryError: No such file or directory -> /home/taskwarrior/.password-store
```

The way the script is set up is to just have hard-coded in the username and password as the `GKEEP_USERNAME` and `GKEEP_PASSWD` environment variables as mentioned [here](https://github.com/bergercookie/syncall/blob/master/readme-tw-gkeep.md#credentials). Is this method no longer supported?

**Comment by oneacik** [comment]
There is an error in code and now it requires GKEEP_TOKEN or it will read it from .password-store.

**Comment by oneacik** [comment]
You can work it around by using:
`export GKEEP_TOKEN="Anything"`

**Comment by oneacik** [comment]
You can work it around by using:
`export GKEEP_TOKEN="Anything"`
